version: 2.1
orbs:
  rust: glotrade/rust@0.1.3
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - rust/build
      - rust/check
      - rust/format
      - rust/test
workflows:
 version: 2
 Example_Workflow:
   jobs:
    - build
